theme: jekyll-theme-cayman
title: Argennon
description: A next-gen blockchain and smart contract platform
show_downloads: "true"
google_analytics: G-TX4F59HBXD
github: 
  repository_url: https://github.com/Argennon-Project
  zip_url: https://github.com/Argennon-Project/ascee/zipball/main
  tar_url: https://github.com/Argennon-Project/ascee/tarball/main
