theme: jekyll-theme-leap-day
title: Argennon
description: A new blockchain and smart contract platform<br><a href="https://twitter.com/Argennon_org?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false">Follow @Argennon_org</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
show_downloads: "true"
google_analytics: G-TX4F59HBXD
